#!/bin/sh

JEXEC="${X11APPJAIL_BASEDIR}/usr/local/libexec/appjail/jexec/jexec"

exec "${JEXEC}" -l \
    -U noroot \
    -e DISPLAY="${X11APPJAIL_DISPLAY}" \
    -e BRAVE_GPU=1 \
    "${X11APPJAIL_JAIL}" \
    brave-browser --ignore-gpu-blocklist "$@"
