#!/bin/sh

set -e -o pipefail

set --
set -- "$@" -j "${X11APPJAIL_JAIL}"
set -- "$@" -f "${X11APPJAIL_WORKDIR}/Makejail"

set -- "$@" -o alias -o ip4_disable -o ip6_disable

if [ -n "${X11APPJAIL_EPHEMERAL}" ] || \
        x11appjail sys-attr check "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.jail.ephemeral" "${X11APPJAIL_UID}"; then
    set -- "$@" -o ephemeral
fi

mkdir -p -m 0755 -- "${X11APPJAIL_USERDIR}"
set -- "$@" -o fstab="${X11APPJAIL_USERDIR} data <volumefs>"

exec "${APPJAIL}" makejail "$@" -- \
    --puid "${X11APPJAIL_UID}" --pgid "${X11APPJAIL_GID}"
