#!/bin/sh

set -o pipefail

BASEDIR=`dirname -- "$0"` || exit $?
BASEDIR=`realpath -- "${BASEDIR}"` || exit $?
SOCKET="${BASEDIR}/sock"

test -S "${SOCKET}" || exit $?

APPNAME="${1}"
SUMMARY="${2}"
BODY="${3}"
BODY=`printf "%s\n" "${BODY}" | base64 -w 0` || exit $?
ICON_PATH="${4}"
URGENCY="${5}"

printf "%s\n%s\n%s\n%s\n%s\n" "${APPNAME}" "${SUMMARY}" "${BODY}" "${ICON_PATH}" "${URGENCY}" | nc -U "${SOCKET}"
