#!/bin/sh

BASEDIR=`dirname -- "$0"` || exit $?
BASEDIR=`realpath -- "${BASEDIR}"` || exit $?

. "${BASEDIR}/app.conf"
. "${BASEDIR}/default.conf"

cd -- "${APPSCRIPT_PWD:-${BASEDIR}}" || exit $?

if [ -n "${APPSCRIPT_SCRIPT}" ] && [ -n "${X11APPJAIL_UNINSTALL}" ]; then
    "${BASEDIR}/uninstall.sh" || exit $?

    if appjail status -q "${X11APPJAIL_JAIL}" > /dev/null 2>&1; then
        appjail stop "${X11APPJAIL_JAIL}"
    fi

    appjail jail destroy -Rf "${X11APPJAIL_JAIL}" > /dev/null 2>&1

    rm -rf "${X11APPJAIL_APPDIR}"
    rm -rf "${X11APPJAIL_SHAREDIR}"
    rm -rf "${X11APPJAIL_LOCKDIR}"

    exit 0
fi

mkdir -p -- "${X11APPJAIL_LOCKDIR}" || exit $?

lockf -ks "${X11APPJAIL_LOCKDIR}/startup.lock" ./startup.sh || exit $?

X11_DISPLAY=`appjail jail list -HI -j "${X11APPJAIL_JAIL}" x11_display` || exit $?

if [ -n "${APPSCRIPT_SCRIPT}" ] && [ -n "${X11APPJAIL_INSTALL}" ]; then
    unset X11APPJAIL_INSTALL

    mkdir -p -- "${X11APPJAIL_APPDIR}" || exit $?
    mkdir -p -- "${X11APPJAIL_SHAREDIR}" || exit $?

    cp -a -- "${APPSCRIPT_SCRIPT}" "${X11APPJAIL_APPDIR}/APPSCRIPT" || exit $?

    {
        echo "#!/bin/sh"
        echo "BASEDIR=\`dirname -- \"\$0\"\` || exit \$?"
        echo "BASEDIR=\`realpath -- \"\${BASEDIR}\"\` || exit \$?"
        export -p | grep -Ee '^export X11APPJAIL_' | sed -Ee 's/^(export X11APPJAIL_([^=]+)=.+)$/test -n "${X11APPJAIL_\2}" || \1/'
        echo "\"\${BASEDIR}/APPSCRIPT\" \"\$@\""
    } > "${X11APPJAIL_APPDIR}/START" || exit $?
    chmod +x "${X11APPJAIL_APPDIR}/START" || exit $?

    "${BASEDIR}/install.sh" || exit $?

    exit 0
fi

if [ -n "${X11APPJAIL_WRAPPER}" ]; then
	exec env X11APPJAIL_DISPLAY="${X11_DISPLAY}" X11APPJAIL_APPBIN="${APPBIN}" \
		"${X11APPJAIL_WRAPPER}" "$@"
elif [ -x "${BASEDIR}/wrapper.sh" ]; then
	exec env X11APPJAIL_DISPLAY="${X11_DISPLAY}" X11APPJAIL_APPBIN="${APPBIN}" \
		"${BASEDIR}/wrapper.sh" "$@"
else
	exec appjail cmd jexec "${X11APPJAIL_JAIL}" -U noroot -e DISPLAY=":${X11_DISPLAY}" "${APPBIN}" "$@"
fi
