#!/bin/sh

BASEDIR=`dirname -- "$0"` || exit $?
BASEDIR=`realpath -- "${BASEDIR}"` || exit $?

. "${BASEDIR}/app.conf"

UID=`id -u` || exit $?
GID=`id -g` || exit $?
PROFILE="${X11APPJAIL_PROFILE:-default}"
X11APPJAIL_JAIL="x11appjail-${APPNAME}-${UID}_${PROFILE}"; export X11APPJAIL_JAIL
LOCKDIR="${X11APPJAIL_LOCKDIR:-${HOME}/x11appjail/locks/${X11APPJAIL_JAIL}}"
APPDIR="${X11APPJAIL_APPDIR:-${HOME}/x11appjail/apps/${X11APPJAIL_JAIL}}"
SHAREDIR="${X11APPJAIL_SHAREDIR:-${HOME}/x11appjail/share/${X11APPJAIL_JAIL}}"

cd -- "${APPSCRIPT_PWD:-${BASEDIR}}" || exit $?

if [ "${APPSCRIPT_SCRIPT}" ] && [ -n "${X11APPJAIL_UNINSTALL}" ]; then
    . "uninstall.sh"

    if appjail status -q "${X11APPJAIL_JAIL}" > /dev/null 2>&1; then
        appjail stop "${X11APPJAIL_JAIL}"
    fi

    rm -rf "${APPDIR}"
    rm -rf "${SHAREDIR}"
    rm -rf "${LOCKDIR}"

    exit 0
fi

mkdir -p -- "${LOCKDIR}" || exit $?

lockf -ks "${LOCKDIR}/startup.lock" ./startup.sh || exit $?

X11_DISPLAY=`appjail jail list -HI -j "${X11APPJAIL_JAIL}" x11_display` || exit $?

if [ -n "${APPSCRIPT_SCRIPT}" ] && [ -n "${X11APPJAIL_INSTALL}" ]; then
    unset X11APPJAIL_INSTALL

    mkdir -p -- "${APPDIR}" || exit $?
    mkdir -p -- "${SHAREDIR}" || exit $?

    cp -a -- "${APPSCRIPT_SCRIPT}" "${APPDIR}/APPSCRIPT" || exit $?

    {
        echo "#!/bin/sh"
        echo "BASEDIR=\`dirname -- \"\$0\"\` || exit \$?"
        echo "BASEDIR=\`realpath -- \"\${BASEDIR}\"\` || exit \$?"
        export -p | grep -Ee '^export X11APPJAIL_' | sed -Ee 's/^(export X11APPJAIL_([^=]+)=.+)$/test -z "${X11APPJAIL_\2}" || \1/'
        echo "\"\${BASEDIR}/APPSCRIPT\" \"\$@\""
    } > "${APPDIR}/START" || exit $?
    chmod +x "${APPDIR}/START" || exit $?

    . "install.sh"
    exit 0
fi

if [ -n "${X11APPJAIL_WRAPPER}" ]; then
	exec env X11APPJAIL_DISPLAY="${X11_DISPLAY}" X11APPJAIL_APPBIN="${APPBIN}" \
		"${X11APPJAIL_WRAPPER}" "$@"
elif [ -x "${BASEDIR}/wrapper.sh" ]; then
	exec env X11APPJAIL_DISPLAY="${X11_DISPLAY}" X11APPJAIL_APPBIN="${APPBIN}" \
		"${BASEDIR}/wrapper.sh" "$@"
else
	exec appjail cmd jexec "${X11APPJAIL_JAIL}" -U noroot -e DISPLAY=":${X11_DISPLAY}" "${APPBIN}" "$@"
fi
