
X11APPJAIL_UID=`id -u` || exit $?
export X11APPJAIL_UID

X11APPJAIL_GID=`id -g` || exit $?
export X11APPJAIL_GID

X11APPJAIL_PROFILE="${X11APPJAIL_PROFILE:-default}"
export X11APPJAIL_PROFILE

X11APPJAIL_JAIL="x11appjail-${APPNAME}-${X11APPJAIL_UID}_${X11APPJAIL_PROFILE}"
export X11APPJAIL_JAIL

X11APPJAIL_LOCKDIR="${X11APPJAIL_LOCKDIR:-${HOME}/x11appjail/locks/${X11APPJAIL_JAIL}}"
export X11APPJAIL_LOCKDIR

X11APPJAIL_APPDIR="${X11APPJAIL_APPDIR:-${HOME}/x11appjail/apps/${X11APPJAIL_JAIL}}"
export X11APPJAIL_APPDIR

X11APPJAIL_SHAREDIR="${X11APPJAIL_SHAREDIR:-${HOME}/x11appjail/share/${X11APPJAIL_JAIL}}"
export X11APPJAIL_SHAREDIR

X11APPJAIL_EXEC_TOOL="${X11APPJAIL_EXEC_TOOL:-doas}"
export X11APPJAIL_EXEC_TOOL

X11APPJAIL_DATADIR="${X11APPJAIL_DATADIR:-${HOME}/x11appjail/data/${X11APPJAIL_JAIL}}"
export X11APPJAIL_DATADIR

X11APPJAIL_CACHEDIR="${X11APPJAIL_CACHEDIR:-${HOME}/x11appjail/cache/${X11APPJAIL_JAIL}}"
export X11APPJAIL_CACHEDIR
