.\"Copyright (c) 2026, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
.\"All rights reserved.
.\"
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"
.\"* Redistributions of source code must retain the above copyright notice, this
.\"  list of conditions and the following disclaimer.
.\"
.\"* Redistributions in binary form must reproduce the above copyright notice,
.\"  this list of conditions and the following disclaimer in the documentation
.\"  and/or other materials provided with the distribution.
.\"
.\"* Neither the name of the copyright holder nor the names of its
.\"  contributors may be used to endorse or promote products derived from
.\"  this software without specific prior written permission.
.\"
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\"DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
.\"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\"SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\"CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\"OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd September 19, 2026
.Dt X11APPJAIL 1
.Os
.Sh NAME
.Nm x11appjail
.Nd Tool for creating, verifying, installing, and running AppJails
.Sh SYNOPSIS
.Nm
.Cm build
.Oo Fl O Oc
.Oo Fl A Ar algo Oc
.Oo Fl a Ar arch Oc
.Oo Fl C Ar directory Oc
.Oo Fl f Ar directory Oc
.Oo Fl i Ar image Oc
.Oo Fl o Ar filename Oc
.Oo Fl s Ar vendorid Ns : Ns Ar public_key Oc
.Oo Fl t Ar tag Oc
.Oo Fl v Ar version Oc
.Ar directory
.Nm
.Cm clipboard
.Oo Fl O Oc
.Oo Fl s Ar selection Oc
.Ar appspec1
.Oo Ar appspec2 Oc
.Nm
.Cm destroy-jail
.Ar appspec
.Nm
.Cm init
.Ar pathname
.Nm
.Cm list
.Nm
.Cm login Ar appspec
.Nm
.Cm prefix
.Nm
.Cm print-display Ar appspec
.Nm
.Cm remove Ar appspec
.Nm
.Cm run Ar appspec Oo Ar args No "..." Oc
.Nm
.Cm run-cmd Ar appspec Oo Ar args No "..." Oc
.Nm
.Cm service Ar service Ar appspec Oo Ar args No "..." Oc
.Nm
.Cm trust Ar vendorid Ar public_key
.Nm
.Cm trusted
.Nm
.Cm untrust Ar vendorid
.Nm
.Cm verify Ar filename
.Nm
.Cm version
.Sh DESCRIPTION
.Nm
is a specialized tool for creating, verifying, installing, and running
AppJails. An AppJail is a CLI, TUI or X11 application that runs
inside a FreeBSD jail but is perceived by the end user as identical
.Pq or at least very similar
to an application running directly on the host system.
.Pp
This tool makes extensive use of
.Xr appjail 1
as its engine; however, unlike the latter, the primary user in
.Nm
is neither root nor a privileged user, but rather an unprivileged user.
The fundamental goal of this project is to grant the user limited
access to the jail, restricted solely to the execution of a
CLI, TUI or X11 application. See also
.Sx SECURITY CONSIDERATIONS Ns "."
.Pp
The options are as follows:
.Pp
.Bl -tag -width xxx
.It Cm build Oo Fl O Oc Oo Fl A Ar algo Oc Oo Fl a Ar arch Oc Oo Fl C Ar directory Oc Oo Fl f Ar directory Oc Oo Fl i Ar image Oc Oo Fl o Ar filename Oc Oo Fl s Ar vendorid Ns : Ns Ar public_key Oc Oo Fl t Ar tag Oc Oo Fl v Ar version Oc Ar directory
Create an AppJail.
.Pp
This command creates an executable using
.Xr appscript 1
that contains an existing
.Xr appjail-image 1 Ns "."
It's recommended to use
.Xr reproduce 1
to create
.Xr appjail-image 1 Ns "s."
.Bl -tag -width xx
.It Fl O
Optimized mode.
.Pp
In the self-contained being created,
.Xr pkg 8
is used to install the packages; consequently, the resulting AppJail
already includes them, so the target system does not need to install
them
.Po including Xr appjail 1 Pc Ns "."
However, these dependencies increase the size of the resulting AppJail
and may result in longer decompression times on the target system.
This option is particularly useful for CLI or TUI applications, or
for small applications, although it can also be used if the target
system installs all the required dependencies.
.It Fl A Ar algo
Compression algorithm to be used to compress
.Ar directory Ns "."
.It Fl a Ar arch
Specifies an architecture different from that of the host.
.Pp
This affects the tools used, such as
.Xr appscript 1 Ns ,
.Xr appjail-image 1 Ns , and
.Xr pkg 8 Ns "."
.It Fl C Ar directory
A directory used to store the packages that
.Xr pkg 8
will download. This could speed up subsequent builds if the
.Fl O
flag isn't set.
.It Fl f Ar directory
Path containing known signatures for the repository, which defaults to
.Pa /usr/share/keys/pkg Ns "."
.Pp
This directory will be copied to
.Pa /usr/share/keys
inside the self-contained environment, so your
.Xr pkg.conf 5
should reflect this in the
.Sy FINGERPRINTS
parameter.
.Pp
If this parameter is set to
.Sy none Ns ,
the fingerprint directory will not be copied.
.It Fl i Ar image
.Xr appjail-image 1
to be copied, or the directory name if this parameter is not specified.
.It Fl o Ar filename
Name of the resulting AppJail.
.Pp
If this parameter is not specified, the directory name with the .AppJail
suffix is used. Only .AppJail or .appjail should be used as extensions,
as this suffix is removed when constructing the application name during
an AppJail execution. Refer to
.Sx IMPLEMENTATION NOTES
for further details.
.It Fl s Ar vendorid Ns : Ns Ar public_key
Sign the resulting AppJail. This is primarily used when planning to run AppJails in portable mode.
.Pp
It is important that the
.Ar vendorid
matches the public key installed on the target system.
.It Fl t Ar tag
.Xr appjail-image 1
tag, which defaults to
.Sy latest Ns "."
.It Fl v Ar version
A number indicating the major version of the FreeBSD ABI to be used.
.Pp
.Xr pkg 8
uses this when installing packages in the self-contained environment,
or, in other words, when the
.Fl O
flag is not specified.
.It Ar directory
The directory containing the files to be included in the AppJail. It is
important that the directory contains a file
.Pq which can be empty
named
.Pa .x11appjail Ns ;
otherwise, this command will not execute. If you previously used
.Cm init Ns , this directory should already contain that dummy file.
.El
.It Cm clipboard Oo Fl O Oc Oo Fl s Ar selection Oc Ar appspec1 Oo Ar appspec2 Oc
Synchronizes the clipboard between two X servers.
.Pp
In essence, it is a wrapper for
.Xr xclipsync 1 Ns ,
but
.Nm
retrieves the
.Ev DISPLAY
for each jail, so only the
.Em appspec
needs to be specified.
.Pp
If only
.Ar appspec1
is specified, the
.Ev DISPLAY
environment variable is used. In other words, this serves to synchronize the clipboard in
.Ar appspec1
with the host's X server.
.Pp
If the
.Fl O
parameter is specified, the clipboard is synchronized only once. See
.Xr xclipsync 1
for details and implications.
.It Cm destroy-jail Ar appspec
Destroy a jail.
.Pp
The user can only destroy jails they own. See
.Sx IMPLEMENTATION NOTES
for further details.
.It Cm init Ar pathname
Create a new directory containing all the files needed to create an
AppJail. Refer to
.Xr x11appjail-spec 5
for details, although the created files contain comments.
.Pp
This command refuses to create the directory if it already exists.
.It Cm list
List all installed AppJails.
.It Cm login Ar appspec
Log into the jail.
.Pp
This command will not work unless the jail has the
.Sy meta.x11appjail.exec.user
parameter set to the user under which
.Xr login 1
will run.
.It Cm prefix
Displays the system prefix, commonly
.Pa /usr/local Ns "."
.It Cm print-display Ar appspec
Displays the
.Ev DISPLAY
assigned by the jail.
.It Cm remove Ar appspec
Uninstalls
.Ar appspec Ns "."
.Pp
Before removing the
.Ar appspec Ns ,
the uninstallation script is executed if it was included in the AppJail.
.It Cm run Ar appspec Oo Ar args No "..." Oc
Executes the program defined by the AppJail inside the jail.
.Pp
If the jail does not exist, it is created. If the checksum has changed,
the jail is recreated. And if the AppJail requires an X server, it will
be created using
.Xr appjail-x11 1
before the application starts.
.Pp
If
.Ar appspec
contains a slash, it runs in portable mode. See
.Sx PORTABLE MODE
for details.
.It Cm run-cmd Ar appspec Oo Ar args No "..." Oc
Executes an arbitrary program inside the jail. If no argument is
specified, the jail user's shell
.Pq or Pa /bin/sh No if none is defined
will be used.
.Pp
This command will not work unless the jail has the
.Sy meta.x11appjail.exec.user
parameter set to the user under which the process will run.
.It Cm service Ar service Ar appspec Oo Ar args No "..." Oc
Configure a
.Ar service
in
.Ar appspec Ns "."
Refer to
.Sx SERVICES
for more details.
.It Cm trust Ar vendorid Ar public_key
Trust a vendor by installing its public key. This will allow AppJails
to run in portable mode. Refer to the
.Sx PORTABLE MODE
section for further details.
.Pp
If
.Ar public_key
is
.Sy -
the content is read from
.Pa /dev/stdin Ns "."
.It Cm trusted Oo Ar pattern Oc
List all trusted providers.
.Pp
If you define a
.Ar pattern
.Po see Xr grep 1 Pc Ns ,
you can shorten the list by searching by comment.
.It Cm untrust Ar vendorid
Removes an installed public key.
.It Cm verify Ar filename
Verify an AppJail.
.Pp
The vendor's public key embedded in the AppJail must be pre-installed;
otherwise, verification will fail.
.It Cm version
Show the version and exit.
.El
.Pp
See
.Sx PROFILES
for an explanation of the meaning of
.Ar appspec Ns "."
.Sh UNPRIVILEGED USERS
As previously mentioned, the main goal of this project is to allow
unprivileged users to run applications inside a jail.
.Nm
uses
.Xr appjail 1 Ns ,
a tool that requires privileges; however, to prevent users from running it
directly while still allowing them to create jails in a restricted manner,
.Nm relies on
.Xr doas 1 Ns "."
You only need to add a single line to your
.Xr doas.conf 5
file:
.Pp
.Bd -literal -compact -offset Ds
.No permit nopass Ar USER No cmd %%PREFIX%%/libexec/x11appjail/map-exec
.Ed
.Pp
Replace
.Ar USER
with the user you want to allow to run AppJails. You can also use a
group for this, so that you do not have to edit your
.Xr doas.conf 5
file every time.
.Pp
.Sy VERY IMPORTANT Ns :
.Pp
.Bl -enum -compact
.It
Do not set
.Sy keepenv Ns "."
Environment variables can affect the execution of the mentioned utility
or the utilities it depends on. You do not need it, and you should not
configure it.
.It
In
.Xr doas.conf 5 Ns ","
the last rules take precedence; therefore, add the previous rule on the
last line.
.Pp
You can run the following command and confirm that the environment is
not inherited:
.Pp
.Bd -literal -compact -offset Ds
 doas %%PREFIX%%/libexec/x11appjail/map-exec env
.Ed
.El
.Sh PORTABLE MODE
Portable mode does not necessarily mean your AppJail is completely free
of dependencies. Depending on how you build your AppJail, it may have
minimal dependencies on
.Xr doas 1
and the utilities located in
.Pa %%PREFIX%%/libexec/x11appjail Ns "."
Consult the
.Sx BUGS
section for the implications of running an AppJail with minimal dependencies.
.Pp
.Dq Portable
means the AppJail does not necessarily require a system-level installation
.Po see Sx INSTALLED APPJAILS No for the counterpart to this mode Pc Ns "."
In this mode, the AppJail can be run like any other
.Xr elf 5
executable. As a minimum requirement, it is assumed that you have correctly
configured
.Xr doas.conf 5
before running an AppJail.
.Pp
However, before creating the jail, starting the X server
.Po if necessary Pc Ns ,
running the application, and performing tasks, the AppJail must be signed
by a trusted vendor. A trusted vendor is one whose public key has been
installed using the
.Cm trust
command.
.Pp
Note that this entails certain performance implications that might not
provide the best user experience for certain applications. Remember that
an AppJail is an executable created by
.Xr appscript 1
that self-extracts to a temporary, deterministic location and is removed
once the last process terminates. This means that when running
.Ql ./<filename>.AppJail
as an unprivileged user, the payload is extracted only once, and the only
task the user process must perform is invoking an internal utility called
.Sy veriexec
.Po which is unrelated to NetBSD's veriexec Pc Ns "."
.Pp
The internal utility,
.Sy veriexec Ns ,
handles verifying the executable using
.Xr appscript-verify 1 Ns ,
which in turn employs
.Xr signify 1
but the steps preceding the program's execution are far more numerous:
.Pp
.Bl -enum -compact
.It
Retrieves the vendor ID embedded in the executable itself.
.It
The vendor ID is hashed using SHA-256, and the public key is expected to be
.Pa /var/x11appjail/keys/sha256(<vendorid>).pub Ns "."
.It
To avoid a TOCTOU race, the executable's SHA-256 checksum is calculated,
and the file is then copied to a deterministic temporary location:
.Pa /tmp/.x11appjail-apps/sha256(<pathname>.AppJail)/<filename>.AppJail Ns "."
.Pp
The filename is safe to preserve, as not all characters are permitted. See the
.Sx IMPLEMENTATION NOTES
for further details.
.It
The executable is verified and, if the verification is successful, it is executed.
.El
.Pp
Note that there is a difference between executing an AppJail via
.Ql ./<filename>.AppJail
and executing it with
.Ql x11appjail run ./<filename>.AppJail
.Ns "."
The first option takes longer and results in higher disk activity and CPU usage, as the payload must be extracted twice: first by the unprivileged user and subsequently by the root user once verification has successfully completed. The only task a user process needs to perform when executing
.Ql ./<filename>.AppJail
is to invoke
.Sy veriexec Ns ,
and that is precisely what
.Ql x11appjail run ./<filename>.AppJail
does.
.Pp
To improve performance in subsequent executions, refer to the
.Sx CACHING
section for details on the techniques employed.
.Pp
An AppJail running in portable mode can only use the default profile. Additionally, the
.Ev X11APPJAIL_EPHEMERAL
environment variable is set, allowing scripts included in the AppJail to use the
.Sy ephemeral
option of
.Xr appjail-quick 1 Ns "."
.Sh CACHING
To improve subsequent executions of the same AppJail, especially when
running it in portable mode
.Pq see Sx PORTABLE MODE
the following techniques are employed to enhance performance without
compromising security:
.Pp
.Bl -enum -compact
.It
Once the checksum is calculated, it is stored in
.Pa /tmp/.x11appjail-apps/sha256(<timestamp>)/ Ns "."
This directory is also used to save the vendor identifier, so that
subsequent executions do not need to retrieve it by extracting it
from the executable.
.Pp
.Sy <timestamp>
is a combination of the executable's absolute path,
.Em ctime Ns , Em mtime Ns , and size in bytes.
.It
Following successful verification, a dummy file is stored in
.Pa /tmp/.x11appjail-apps/sha256(<pathname>)/
to serve as an indicator for future processes, making it unnecessary
to call
.Xr appscript-verify 1
again.
.El
.Pp
Using the aforementioned techniques will save a considerable amount of
disk activity and CPU time.
.Pp
The directories used in that shared location belong to user and group
.Sy 0:0 Ns ,
and a check is performed when they exist. This prevents unprivileged
users from tampering with the cache results.
.Pp
Another technique used when running an AppJail involves executing it in the background with the
.Fl Fl cache
option enabled, which simply runs
.Xr sleep 1
for a specified duration. The underlying idea is that, because a process is using the extracted directory, the directory is not removed. Each time the AppJail runs, a timestamp is updated and the process continues to execute. The default duration for this process is 30m, though this can be modified by configuring
.Sy x11appjail_cache_ttl
in the
.Xr rc.conf 5
file.
.Pp
All of this happens implicitly, and the user does not need to do anything.
.Sh INSTALLED APPJAILS
This is the recommended way to run an AppJail: simply by installing it
and then running it.
.Pp
When an AppJail is installed, for example, by running
.Ql ./<filename>.AppJail --install
as root, the appdir is installed at
.Pa /var/x11appjail/apps/<app>.<profile> Ns "."
This means that when running
.Ql x11appjail run <appspec>
.Ns , there is no need to extract the payload, and performance improves
significantly.
.Pp
This also means that there is no need to use the caching techniques described in
.Sx CACHING Ns ,
and the user experience will be better.
.Pp
An installed AppJail also enables another useful feature: profiles, described in better in
.Sx PROFILES Ns "."
.Sh PROFILES
.Ar appspec
consists of
.Ar appname Ns Oo : Ns Ar profile Oc Ns "."
.Ar appname
depends on the filename and not all characters are allowed. A profile is
another instance of the same application; this entails using a separate
user directory for persistent data storage and a different jail. Profiles
are useful for using the same application across different use cases while
keeping them isolated from one another.
.Sh SERVICES
Services allow the jail to execute a specific task on the host in a
limited manner.
.Pp
The following are the available services:
.Pp
.Bl -tag -width xxx
.It Ic OpenURL Ar appspec Oo Fl a Ar patterns Oc
Allow the jail to open a URL.
.Pp
Before opening a URL with
.Xr xdg-open 1 Ns ,
the user is prompted to allow or deny opening the URL.
.Pp
If the URL matches a list of regular expressions
.Xr grep 1 No Po with extended regular expressions Pc Ns "."
defined by the
.Fl a
option, no confirmation dialog is displayed and the URL is opened directly.
.br
If it does not match or if this list of regular expressions is not defined, a confirmation dialog box is displayed, and the URL is shown in percent-encoded format for non-ASCII
.Po 7-bit Pc
characters and the
.Li "
character, so that even invisible Unicode characters can be parsed in this way. The
.Li "
character is percent-encoded because this character is already used in the dialog box where the URL is displayed. However, even though the URL is shown in percent-encoded for non-ASCII (7-bit) characters and the
.Li "
character, the URL is passed as-is.
.It Ic Notification Ar appspec
Allow the jail to notify the host using
.Xr notify-send 1 Ns "."
.Pp
Note that
.Em sysutils/dunst
must be installed in the jail for this to work.
.Pp
This service receives the app name, summary, body
.Po base64-encoded Pc Ns ,
icon path, and urgency of a notification created from a jail via stdin.
.br
The message body may contain special characters, such as newlines, tabs,
etc., but the rendering of these characters depends entirely on your
system's notification daemon, which typically supports a limited number
of HTML tags. The icon path is completely ignored, and AppJail's icon is
used instead.
.br
After receiving the first input, the app name, this service
will wait for the remaining inputs, but with a timeout set to 1 second to
prevent a malicious behaviour by the jail.
.br
Once all parameters have been received and the body has been successfully decoded,
.Xr notify-send 1
is used to create a notification.
.El
.Pp
System services are stored in
.Pa %%PREFIX%%/libexec/x11appjail/service.d/<service>/ Ns ,
while user services are stored in
.Pa %%PREFIX%%/etc/x11appjail/service.d/<service>/ Ns "."
User services take precedence over system services. Regardless of whether
a service is a system or user service, it always runs with the privileges
of the invoking process and never as root; this is because services must
inherit the user's environment.
.Pp
It is strongly recommended to limit the scope of services to a single
task and to assume that any input from the jail is untrusted. See
.Xr sprog 7
for relevant recommendations.
.Sh IMPLEMENTATION NOTES
The AppJail filename serves as the application name used to construct other strings, such as the name of the jail where the application will run and the data directory used for data persistence, among other things.
.Pp
The profile, the filename, and, by extension, the application name must conform to the following pattern:
.Qo Sy "^[a-zA-Z0-9][a-zA-Z0-9_-]*$" Qc Ns "."
.Pp
The jail name is constructed by concatenating the prefix
.Sy x11appjail- Ns ,
the application name, the UID of the calling process, and the suffix
.Sy _ Ar profile Ns "."
For example, if a user with UID
.Sy 15000
executes
.Pa ./htop.AppJail Ns ,
a jail named
.Sy x11appjail-htop-15000_default
will be created. Since the user is running this AppJail in portable mode,
only the default profile can be used.
.Sh ENVIRONMENT
.Bl -tag -width xx
.It Ev DISPLAY
The X server to which
.Xr Xephyr 1
will connect. See
.Xr appjail-x11 1
for more information.
.Pp
Note that this environment variable must match the following pattern to
be considered valid:
.Qo Sy "^(unix|localhost|127\.0\.0\.1|\[::1\])?:[0-9]+(\.[0-9]+)?$" Qc
.El
.Sh FILES
The following directories are created when the process invoking an
AppJail is root:
.Pp
.Bl -tag -width xx
.It Pa /var/x11appjail/apps
Location of installed AppJails.
.It Pa /var/x11appjail/keys
Location of the vendors' public keys.
.It Pa /var/x11appjail/users
Location of data directories used by users.
.Pp
.Nm
will not create this directory or its subdirectories. It is the
responsibility of the AppJails to create this directory and
conventionally map the unprivileged user's UID and GID so that
the user can access those files from the host.
.It Pa /var/run/x11appjail-cache
Location of the directory used by the background process when AppJail
is invoked with the
.Fl Fl cache
parameter. See the
.Sx CACHING
section for more details.
.It Pa /tmp/.x11appjail-locks
Location of the file locks used by the AppJail.
.It Pa /tmp/.x11appjail-apps
Location of the cache system when running an AppJail in portable mode.
See the
.Sx CACHING
section for details.
.El
.Pp
The following directories are created when the process invoking an
AppJail is an unprivileged user:
.Pp
.Bl -tag -width xx
.It Pa ~/.x11appjail/apps
Equivalent to
.Pa /var/x11appjail/apps Ns ,
but unlike that directory, when an AppJail is installed by an unprivileged
user, the binary is copied instead of the application directory. This means
that, even when installing an AppJail as an unprivileged user, it always
runs in portable mode.
.It Pa ~/.x11appjail/run
Equivalent to
.Pa /var/run/x11appjail-cache
but for unprivileged users.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr appjail 1
.Xr appjail-image 1
.Xr appjail-x11 1
.Xr appscript 1
.Xr appscript-verify 1
.Xr doas 1
.Xr reproduce 1
.Xr signify 1
.Xr xclipsync 1
.Xr sysexits 3
.Xr x11appjail-spec 5
.Sh AUTHORS
.An Jesús Daniel Colmenares Oviedo Aq Mt DtxdF@disroot.org
.Sh BUGS
Technically speaking, an AppJail can run with minimal dependencies. For
instance, an AppJail will detect whether the host has
.Xr appjail 1
installed and will prefer using that version over the one bundled within
the executable itself. The reason lies in Virtual Networks: virtual
networks require calculating the next IPv4 address from a shared
address pool, making it illogical to perform this operation from
within a private directory; hence, using the
.Xr appjail 1
installed on the host is preferable. Likewise, certain
.Nm
commands, such as
.Cm print-display Ns , Cm destroy-jail No or Cm clipboard
will not work, as they rely on
.Xr appjail 1
installed on the host.
.Pp
Since virtual networks need to share the same address pool, an AppJail
with minimal dependencies can either inherit the host's network
stack or disable the jail's own network stack entirely, thereby
limiting available networking options. While other network
configurations are possible, they depend entirely on how
the AppJail was created.
.Pp
It is possible to create an AppJail with minimal dependencies
.Po meaning it requires only Xr doas 1 No and Nm Pc
by omitting the
.Fl O
option from the
.Cm build
command. When this option is omitted, all dependencies are bundled into
the binary, making it fully self-contained and eliminating the need for
the host to have them installed. However, this increases the size of
the AppJail; if the host already possesses the necessary dependencies,
such bundling is entirely unnecessary.
.Sh SECURITY CONSIDERATIONS
Physical access constitutes a privilege in itself.
.Pp
The primary goal of this project is to run applications within jails
without needing to become root or allowing unprivileged users to use
.Xr appjail 1
directly; however, this does not mean you should allow just any user
to run AppJails, for the following reasons:
.Pp
.Bl -enum -compact
.It
Considerable effort is devoted to validating that user-provided files do
not interfere with the execution of utilities running with root privileges;
however, the size of these files is not verified. This is because it is
assumed that if a user has permission to run AppJails and is not subject to
quotas limiting the size of stored files, the size of those files should not
pose a problem for the system as a whole.
.It
The temporary directory is extensively used by both x11appjail and
.Xr appscript 1 Ns "."
Although significant effort goes into employing caching techniques to reduce
disk activity and CPU time, the user could potentially invalidate the cache,
forcing
.Nm
and its associated components to revalidate the entire process.
.It
An AppJail's filename is used when creating a jail, as it serves as the
jail's name. This means a user can create multiple copies of the same
AppJail using different filenames, resulting in the creation of distinct
jails. Although each jail is isolated, this implies that the system will
eventually contain numerous jails.
.El
.Pp
In the context of
.Nm Ns ,
a trusted user is one who does not present the issues mentioned above.
Generally, a user with physical access is considered trusted. If you
have full control over your system, you are a trusted user.
.Pp
Even if you have root privileges or are the system's sole user, you can
use AppJails to protect your host machine. The proper approach is not to
trust the jails and to assume they are already compromised; this implies
that clipboard usage and file sharing can pose a risk.
.Pp
Finally, remember that when installing an AppJail as root, it runs without invoking
.Nm Ns 's
.Sy veriexec Ns ,
unlike when it runs as an unprivileged user. This is because the binary has
already been executed, so verifying the executable serves no purpose.
.Nm Ns 's
.Sy veriexec
is implemented solely to protect the host when an unprivileged user runs
an AppJail; the reverse scenario makes no sense. If you wish to verify an
executable before running it as root, you can use the
.Cm verify
command prior to execution.
