#!/bin/sh
#
# Copyright (c) 2026, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -o pipefail

ATTRDIR="/var/x11appjail/attrs"

load_common()
{
    local prefix
    prefix=`x11appjail prefix` || exit 1

    . "${prefix}/lib/x11appjail/common"
}

load_common

ME=`readlink -f -- "$0"` || exit 1
ME=`basename -- "${ME}"` || exit 1

case "${ME}" in
    attr) TYPE="user" ;;
    sys-attr) TYPE="system" ;;
    *) exit 1 ;;
esac

OPERATION="$1"

test -n "${OPERATION}" || exit 1

case "${OPERATION}" in
    put|rm|cat) ;;
    *) exit 1 ;;
esac

ATTR="$2"

test -n "${ATTR}" || exit 1

if ! check_attr "${ATTR}"; then
    err "Invalid attribute: ${ATTR}"
    exit 1
fi

VALUE=

if [ "${OPERATION}" = "put" ]; then
    VALUE="$3"
fi

if [ "${TYPE}" = "user" ]; then
    test -n "${DOAS_USER}" || exit 1

    UID=`id -u "${DOAS_USER}"` || exit 1

    ATTRDIR="${ATTRDIR}/users/${UID}"
else
    if ! iam_root; then
        exit 1
    fi

    if [ "${OPERATION}" = "put" ]; then
        UID="$4"
    else
        UID="$3"
    fi

    if [ -z "${UID}" ]; then
        ATTRDIR="${ATTRDIR}/system"
    else
        UID=`id -u -- "${UID}"` || exit 1
        ATTRDIR="${ATTRDIR}/users/${UID}"
        TYPE="user"
    fi
fi

ATTR_FILE="${ATTRDIR}/${ATTR}"

create_directory "${ATTRDIR}"

if [ "${OPERATION}" = "cat" -o "${OPERATION}" = "rm" ]; then
    if [ ! -f "${ATTR_FILE}" ]; then
        if [ -n "${UID}" ]; then
            err "${ATTR} (${UID}): ${TYPE} attribute not found."
        else
            err "${ATTR}: ${TYPE} attribute not found."
        fi
        exit 1
    fi
fi

(
    lockf 9 || exit 1

    if [ "${OPERATION}" = "put" ]; then
        create_file "${ATTR_FILE}"
        
        printf "%s" "${VALUE}" | head -n 1 | head -c 4096 >&9 || exit 1
    elif [ "${OPERATION}" = "cat" ]; then
        VALUE=`cat -- "${ATTR_FILE}" | head -n 1 | head -c 4096` || exit 1

        if [ -n "${VALUE}" ]; then
            printf "%s\n" "${VALUE}" || exit 1
        else
            printf "%s" "${VALUE}" || exit 1
        fi
    elif [ "${OPERATION}" = "rm" ]; then
        rm -f -- "${ATTR_FILE}" || exit 1
    fi
) 9>> "${ATTR_FILE}" || exit 1
exec 9>&-
