#!/bin/sh
#
# Copyright (c) 2026, Jesús Daniel Colmenares Oviedo <DtxdF@disroot.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -o pipefail

test -n "${DOAS_USER}" || exit 1

UID=`id -u "${DOAS_USER}"` || exit 1
GID=`id -g "${DOAS_USER}"` || exit 1

load_common()
{
    local _s
    _s=`which x11appjail` || exit ${EX_SOFTWARE}
    _s=`dirname -- "${_s}"` || exit ${EX_SOFTWARE}
    _s="${_s}/../lib/x11appjail"

    LIBDIR="${_s}"

    . "${LIBDIR}/common"
}

check_appspec()
{
    printf "%s" "$1" | grep -qEe '^[^:]+:.*$'
}

load_common

FILE_MODE="$1"

test -n "${FILE_MODE}" || exit 1

FROM="$2"

test -n "${FROM}" || exit 1

FROM_APPSPEC=
FROM_FILE=
FROM_APPNAME=
FROM_PROFILE=

if check_appspec "${FROM}"; then
    FROM_APPSPEC=`printf "%s" "${FROM}" | cut -d: -f1` || exit 1
    FROM_FILE=`printf "%s" "${FROM}" | cut -d: -f2-` || exit 1

    build_appspec "${FROM_APPSPEC}"

    FROM_APPNAME="${APPNAME}"
    FROM_PROFILE="${PROFILE}"
else
    FROM_FILE="${FROM}"
fi

TO="$3"

TO_APPSPEC=
TO_FILE=
TO_APPNAME=
TO_PROFILE=

if [ -n "${TO}" ]; then
    if check_appspec "${TO}"; then
        TO_APPSPEC=`printf "%s" "${TO}" | cut -d: -f1` || exit 1
        TO_FILE=`printf "%s" "${TO}" | cut -d: -f2-` || exit 1

        build_appspec "${TO_APPSPEC}"

        TO_APPNAME="${APPNAME}"
        TO_PROFILE="${PROFILE}"
    else
        TO_FILE="${TO}"
    fi
else
    if [ -z "${FROM_APPSPEC}" ]; then
        err "Source must be defined to continue."
        exit 1
    fi
fi

if [ -n "${FROM_APPSPEC}" -a -n "${FROM_FILE}" ]; then
    jtransfer -r \
        -u "${UID}:${GID}" \
        -j "x11appjail-${FROM_APPNAME}-${UID}_${FROM_PROFILE}" \
        -f "${FROM_FILE}" || exit 1
else
    su-exec "${UID}:${GID}" cat -- \
        "${FROM_FILE}" || exit 1
fi |\
if [ -n "${TO_APPSPEC}" -a -n "${TO_FILE}" ]; then
    jtransfer -w \
        -m "${FILE_MODE}" \
        -u "${UID}:${GID}" \
        -j "x11appjail-${TO_APPNAME}-${UID}_${TO_PROFILE}" \
        -f "${TO_FILE}" || exit 1
elif [ -n "${TO_FILE}" ]; then
    su-exec "${UID}:${GID}" tee "${TO_FILE}" > /dev/null || exit 1
else
    cat -u || exit 1
fi
