#!/bin/sh

set -e -o pipefail

NORM_APPNAME=`printf "%s" "${X11APPJAIL_APPNAME}" | sed -Ee 's/-/__/g'`
NORM_PROFILE=`printf "%s" "${X11APPJAIL_PROFILE}" | sed -Ee 's/-/__/g'`

OPTIONS=`sysrc -ni "x11appjail_options" || :`
if [ -z "${OPTIONS}" ]; then
    OPTIONS=`sysrc -ni "x11appjail_${NORM_APPNAME}_options" || :`
fi
if [ -z "${OPTIONS}" ]; then
    OPTIONS=`sysrc -ni "x11appjail_${NORM_APPNAME}_${NORM_PROFILE}_options" || :`
fi

if [ -z "${X11APPJAIL_NETWORK_MODE}" ]; then
    X11APPJAIL_NETWORK_MODE=`sysrc -ni x11appjail_network_mode || :`
fi

NETWORK_MODE="${X11APPJAIL_NETWORK_MODE:-none}"

set --
set -- "$@" -j "${X11APPJAIL_JAIL}"
set -- "$@" -f "${X11APPJAIL_WORKDIR}/Makejail"

if [ "${NETWORK_MODE}" = "inherit" ]; then
    set -- "$@" -o alias -o ip4_inherit -o ip6_inherit
elif [ "${NETWORK_MODE}" = "virtualnet" ]; then
    if [ "${APPJAIL_SELF_CONTAINED}" != 0 ]; then
        echo "ERROR: Virtual Networks requires AppJail to be installed on the host."
    fi

    set -- "$@" -o virtualnet="${X11APPJAIL_VIRTUALNET}:<random> default" -o nat
else
    if [ "${NETWORK_MODE}" != "none" ]; then
        echo "WARNING: invalid network mode '${NETWORK_MODE}', falling back to 'none'" >&2
    fi
    set -- "$@" -o alias -o ip4_disable -o ip6_disable
fi

if [ "${NETWORK_MODE}" = "virtualnet" ]; then
    SECGRP_TABLE=`sysrc -ni x11appjail_secgrp_table || :`

    if [ -n "${SECGRP_TABLE}" ]; then
        set -- "$@" -o label="security-group:1"
        set -- "$@" -o label="security-group.tables.${SECGRP_TABLE}:${SECGRP_TABLE}"
    fi
fi

set -- "$@" -o mount_devfs
set -- "$@" -o device='include $devfsrules_hide_all'
set -- "$@" -o device='include $devfsrules_unhide_basic'
set -- "$@" -o device='include $devfsrules_unhide_login'

SOUND_ALREADY=false

for OPTION in ${OPTIONS}; do
    if [ -n "${X11APPJAIL_ENABLE_SOUND}" ] || [ "${OPTION}" = "sound" ]; then
        ${SOUND_ALREADY} && continue

        set -- "$@" -o device="path sndstat unhide"
        set -- "$@" -o device="path mixer unhide"
        set -- "$@" -o device="path 'mixer*' unhide"
        set -- "$@" -o device="path dsp unhide"
        set -- "$@" -o device="path 'dsp*' unhide"
        set -- "$@" -o device="path speaker unhide"
        set -- "$@" -o device="path 'speaker*' unhide"

        SOUND_ALREADY=true
    fi
done

if [ -n "${X11APPJAIL_EPHEMERAL}" ]; then
    set -- "$@" -o ephemeral
fi

if [ -n "${X11APPJAIL_LABEL0}" ]; then
    labels=`mktemp -d -t x11appjail`
    index=0

    env | grep -Ee '^X11APPJAIL_LABEL[0-9]+=.*$' | while IFS= read -r env; do
        value=`printf "%s" "${env}" | cut -d= -f2-`

        printf "%s\n" "${value}" > "${labels}/${index}"

        index=$((index+1))
    done

    for label_file in "${labels}"/*; do
        label=`head -1 -- "${label_file}"`

        set -- "$@" -o label="${label}"
    done

    rm -rf -- "${labels}"
    unset labels index label_file label
fi

mkdir -p -m 0755 -- "${X11APPJAIL_USERDIR}"
set -- "$@" -o fstab="${X11APPJAIL_USERDIR} data <volumefs>"

exec "${APPJAIL}" makejail "$@" -- \
    --puid "${X11APPJAIL_UID}" --pgid "${X11APPJAIL_GID}"
