#!/bin/sh

set -e -o pipefail

ME=`readlink -f -- "$0"`
SELF=`dirname -- "${ME}"`
SOCKET="${SELF}/sock"

test -S "${SOCKET}"

APPNAME="${1}"
SUMMARY="${2}"
BODY="${3}"
BODY=`printf "%s\n" "${BODY}" | base64 -w 0`
ICON_PATH="${4}"
URGENCY="${5}"

printf "%s\n%s\n%s\n%s\n%s\n" "${APPNAME}" "${SUMMARY}" "${BODY}" "${ICON_PATH}" "${URGENCY}" | nc -U "${SOCKET}"
