#!/bin/sh

set -o pipefail

JEXEC="${X11APPJAIL_BASEDIR}/usr/local/libexec/appjail/jexec/jexec"

ME="${APPSCRIPT_SCRIPT:-x11appjail run ${X11APPJAIL_APPNAME}}"
OUTPUT_TMPDIR=
IGNORED_SIGNALS="SIGALRM SIGVTALRM SIGPROF SIGUSR1 SIGUSR2"
HANDLED_SIGNALS="SIGTERM SIGQUIT SIGINT SIGHUP"

OPT_NEW_WINDOW=false
OPT_FULLSCREEN=false
OPT_PRESENTATION=false
OPT_PREVIEW=false
OPT_PAGE_LABEL=
OPT_PAGE_INDEX=
OPT_NAMED_DEST=
OPT_FIND=
OPT_CACHE=true
OPT_WITH_PUCK=false
OPT_PUCK_RESOLUTION=300
OPT_PUCK_BATCH=50

err()
{
    printf "###> %s\n" "$*" >&2
}

run_as()
{
    HOME="${X11APPJAIL_HOMEDIR}" \
        mdo -u "${X11APPJAIL_UID}" -g "${X11APPJAIL_GID}" -G "${X11APPJAIL_OGID}" -- "$@"
}

remove_tmpdir()
{
    if [ -n "${OUTPUT_TMPDIR}" ] && [ -d "${OUTPUT_TMPDIR}" ]; then
        rm -rf -- "${OUTPUT_TMPDIR}"
    fi
}

atexit_init()
{
    trap '' ${IGNORED_SIGNALS}
    trap clean_exit ${HANDLED_SIGNALS}
    trap "_ERRLEVEL=\$?; _clean_exit; exit \${_ERRLEVEL}" EXIT
}

clean_exit()
{
    ignore_signals
    _clean_exit
    trap - ${IGNORED_SIGNALS} ${HANDLED_SIGNALS}

    exit ${EX_SOFTWARE}
}

ignore_signals()
{
    trap '' ${HANDLED_SIGNALS}
}

_clean_exit()
{
    remove_tmpdir
}

help()
{
    cat << EOF
usage: ${ME} [options] [<file>]

Description:

  This AppJail opens a document using Evince within a FreeBSD jail in a
  secure manner:

    1. The jail has no network stack.
    2. The document is always read as the unprivileged user, except when
       the file is transferred to a root-controlled directory.
    3. When used in conjunction with Puck, a potentially untrusted PDF
       can be converted into a trusted one before being read.

  To improve performance for subsequent operations, the document is cached
  in the user directory using its checksum as the filename and without an
  extension. See \`\${X11APPJAIL_USERDIR}\` in \`x11appjail-spec(5)\`.

  Blake3 is used instead of SHA-256 to speed up checksum calculation, but
  this requires \`sysutils/b3sum\` to be installed. If this dependency is
  not installed, SHA-256 is used as a fallback, unless
  \`x11appjail_checksum_algo\` has been set to \`sha256\` in the
  \`rc.conf(5)\` file.

  There are three ways to use this AppJail:

    1. Open without arguments.
    2. Open using \`--new-window\` as an argument.
    3. Open by specifying the document to be read as an argument.

Options:

  -?, -h, --help
        Show this help message and exit.

  -o, --new-window
        Open a new window.

  -p, --page-label <PAGE>
        The page label of the document to display.

  -i, --page-index <NUMBER>
        The page number of the document to display.

  -n, --named-dest <DEST>
        Named destination to display.

  -f, --fullscreen
        Run evince in fullscreen mode.

  -s, --presentation
        Run evince in presentation mode.

  -w, --preview
        Run evince as a previewer.

  -l, --find <STRING>
        The word or phrase to find in the document.

  --without-cache
        Don't use the cached file. Always overwrite it.

  --with-puck
  --puck-resolution <RESOLUTION> (default: 300)
  --puck-batch <NUMBER> (default: 50)
        Use puck to convert a potentially untrusted PDF into a trusted one.

        See also: https://github.com/AppJail-makejails/puck
EOF
}

atexit_init

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)
            help
            exit 0
            ;;
        -o|--new-window)
            OPT_NEW_WINDOW=true
            ;;
        -f|--fullscreen)
            OPT_FULLSCREEN=true
            ;;
        -s|--presentation)
            OPT_PRESENTATION=true
            ;;
        -w|--preview)
            OPT_PREVIEW=true
            ;;
        -p|--page-label)
            if [ "$2" = "" ]; then
                usage
                return ${EX_USAGE}
            fi

            OPT_PAGE_LABEL="$2"
            shift
            ;;
        -i|--page-index)
            if [ "$2" = "" ]; then
                usage
                return ${EX_USAGE}
            fi

            OPT_PAGE_INDEX="$2"
            shift
            ;;
        -n|--named-dest)
            if [ "$2" = "" ]; then
                usage
                return ${EX_USAGE}
            fi

            OPT_NAMED_DEST="$2"
            shift
            ;;
        -l|--find)
            if [ "$2" = "" ]; then
                usage
                return ${EX_USAGE}
            fi

            OPT_FIND="$2"
            shift
            ;;
        --without-cache)
            OPT_CACHE=false
            ;;
        --with-puck)
            OPT_WITH_PUCK=true
            ;;
        --puck-resolution)
            if [ "$2" = "" ]; then
                usage
                return ${EX_USAGE}
            fi

            OPT_PUCK_RESOLUTION="$2"
            shift
            ;;
        --puck-batch)
            if [ "$2" = "" ]; then
                usage
                return ${EX_USAGE}
            fi

            OPT_PUCK_BATCH="$2"
            shift
            ;;
        -*)
            err "'$1' is invalid. Use '--help' to see a list of all available options."
            exit 1
            ;;
        *)
            break
            ;;
    esac
    shift
done

if ${OPT_NEW_WINDOW}; then
    exec "${JEXEC}" -l \
        -U noroot \
        -e DISPLAY="${X11APPJAIL_DISPLAY}" \
        "${X11APPJAIL_JAIL}" \
        evince --new-window
    exit $?
fi

FILE="$1"

if [ -z "${FILE}" ]; then
    exec "${JEXEC}" -l \
        -U noroot \
        -e DISPLAY="${X11APPJAIL_DISPLAY}" \
        "${X11APPJAIL_JAIL}" \
        evince
    exit $?
fi

FILE="${FILE#file://}"

if run_as [ ! -f "${FILE}" ]; then
    err "${FILE}: file not found or no read permission."
    exit 1
fi

ALGO=`sysrc -ni x11appjail_checksum_algo`

if [ -z "${ALGO}" ]; then
    if which -s b3sum; then
        ALGO="blake3"
    else
        ALGO="sha256"
    fi
fi

if [ "${ALGO}" = "blake3" ]; then
    CHECKSUM=`run_as b3sum --no-names -- "${FILE}"` || exit 1
else # Ignore an invalid algorithm implicitly.
    CHECKSUM=`run_as sha256 -q -- "${FILE}"` || exit 1
fi

OUTPUT="${X11APPJAIL_USERDIR}/${CHECKSUM}"

if ! ${OPT_CACHE} || [ ! -f "${OUTPUT}" ]; then
    rm -f -- "${OUTPUT}"

    OUTPUT_TMPDIR=`mktemp -d -t x11appjail` || exit 1

    # Any file would be valid if the calling process could read it.
    run_as cat -- "${FILE}" | cat > "${OUTPUT_TMPDIR}/file" || exit 1

    if ${OPT_WITH_PUCK}; then
        FILE="${OUTPUT_TMPDIR}/file"

        "${APPJAIL}" makejail \
            -f gh+AppJail-makejails/puck \
            -o container="args:--pull=newer" \
            -V PUCK_RESOLUTION="${OPT_PUCK_RESOLUTION}" \
            -V PUCK_BATCH="${OPT_PUCK_BATCH}" \
            -V PUCK_COMPRESSION="0" \
            -- \
                --puck_file "${FILE}" \
                --puck_output "${OUTPUT_TMPDIR}" || exit 1

        INPUT_FILE="${OUTPUT_TMPDIR}/file.trusted.pdf"
    else
        INPUT_FILE="${OUTPUT_TMPDIR}/file"
    fi

    cat -- "${INPUT_FILE}" |\
        "${JEXEC}" -l -U noroot "${X11APPJAIL_JAIL}" sh -c "cat > \"\${HOME}/.${CHECKSUM}.partial\"" || exit 1

    remove_tmpdir

    "${JEXEC}" -l -U noroot "${X11APPJAIL_JAIL}" \
        sh -c "mv -h -- \"\${HOME}/.${CHECKSUM}.partial\" \"\${HOME}/${CHECKSUM}\"" || exit 1
fi

OUTPUT=`"${JEXEC}" -l -U noroot "${X11APPJAIL_JAIL}" sh -c "echo \\\${HOME}"` || exit 1
OUTPUT="${OUTPUT}/${CHECKSUM}"

set --

if ${OPT_FULLSCREEN}; then
    set -- --fullscreen
elif ${OPT_PRESENTATION}; then
    set -- --presentation
elif ${OPT_PREVIEW}; then
    set -- --preview
fi

if [ -n "${OPT_PAGE_LABEL}" ]; then
    set -- "$@" --page-label="${OPT_PAGE_LABEL}"
elif [ -n "${OPT_PAGE_INDEX}" ]; then
    set -- "$@" --page-index="${OPT_PAGE_INDEX}"
elif [ -n "${OPT_NAMED_DEST}" ]; then
    set -- "$@" --named-dest="${OPT_NAMED_DEST}"
fi

if [ -n "${OPT_FIND}" ]; then
    set -- "$@" --find="${OPT_FIND}"
fi

set -- "$@" -- "${OUTPUT}"

exec "${JEXEC}" -l \
    -U noroot \
    -e DISPLAY="${X11APPJAIL_DISPLAY}" \
    "${X11APPJAIL_JAIL}" \
    evince "$@"
