#!/bin/sh

BASEDIR=`dirname -- "$0"` || exit $?
BASEDIR=`realpath -- "${BASEDIR}"` || exit $?

APPNAME="nanonote"
UID=`id -u` || exit $?
PROFILE="${X11APPJAIL_PROFILE:-default}"
X11APPJAIL_JAIL="x11appjail-${APPNAME}-${UID}_${PROFILE}"; export X11APPJAIL_JAIL

cd -- "${APPSCRIPT_PWD:-${BASEDIR}}" || exit $?

LOCKDIR="${X11APPJAIL_LOCKDIR:-${HOME}/x11appjail/locks/${JAIL}}"

mkdir -p -- "${LOCKDIR}" || exit $?

lockf -ks "${LOCKDIR}/startup.lock" ./startup.sh || exit $?

while :; do
    XEPHYR_PID=`appjail jail list -HI -j "${X11APPJAIL_JAIL}" xephyr_pid` || exit $?

    if [ -n "${XEPHYR_PID}" ]; then
        break
    fi

    sleep 1 || exit $?
done

X11_DISPLAY=`appjail jail list -HI -j "${X11APPJAIL_JAIL}" x11_display` || exit $?

exec appjail cmd jexec "${X11APPJAIL_JAIL}" -U noroot -e DISPLAY=":${X11_DISPLAY}" nanonote "$@"
