#!/bin/sh

set -o pipefail

BASEDIR=`dirname -- "$0"` || exit $?
BASEDIR=`realpath -- "${BASEDIR}"` || exit $?
SOCKET="${BASEDIR}/sock"

test -S "${SOCKET}" || exit $?

printf "%s\n" "$1" | nc -U "${SOCKET}"
