#!/bin/sh

if [ -n "${X11APPJAIL_DEBUG}" ]; then
    set -x
fi

BASEDIR=`dirname -- "$0"` || exit $?
BASEDIR=`realpath -- "${BASEDIR}"` || exit $?

. "${BASEDIR}/../../app.conf"
. "${BASEDIR}/../../default.conf"

read URL

escape_url()
{
    printf '%s' "$1" | od -v -An -t u1 | awk '
{
    for (i = 1; i <= NF; i++) {
        if ($i >= 32 && $i <= 126 && $i != 34) {
            printf("%c", $i)
        } else {
            printf("%%%02X", $i)
        }
    }
}'
}

dbus_run_session()
{
    if which -s "dbus-run-session"; then
        dbus-run-session "$@"
        return $?
    fi

    local _o
    while getopts ":" _o; do done
    shift $((OPTIND-1))

    "$@"
}

open_url=false

for ALLOW in ${X11APPJAIL_SRV_OPENURL_ALLOW}; do
    if printf "%s" "${URL}" | grep -qEe "${ALLOW}"; then
        open_url=true
        break
    fi
done

if ! ${open_url}; then
    if ! which -s "zenity"; then
        "${X11APPJAIL_EXEC_TOOL}" pkg install -y zenity4 >&2 || exit $?
    fi

    DISPLAY_URL=`escape_url "${URL}"` || exit $?

    printf "%s" "${DISPLAY_URL}" | LANG=en_US.UTF-8 dbus_run_session -- zenity --text-info \
        --no-markup \
        --width=420 \
        --title="[${X11APPJAIL_SERVICE_FROM}] Do you want to open this URL in [${APPNAME}:${X11APPJAIL_PROFILE}]?" \
        --ok-label="Yes" \
        --cancel-label="No"

    if [ $? -eq 0 ]; then
        open_url=true
    else
        open_url=false
    fi
fi

WRAPPER="${X11APPJAIL_APPDIR}/START"

if ${open_url}; then
    unset X11APPJAIL_SERVICE
    unset X11APPJAIL_SERVICE_FROM

    exec "${WRAPPER}" -- "${URL}"
fi

exit 0
