#!/bin/sh

appjail status -q -- "${JAIL}" > /dev/null 2>&1

ERRLEVEL=$?

if [ ${ERRLEVEL} -ne 0 ]; then
    exit 0
fi

DEFAULT_WEB_BROWSER=`appjail cmd jexec "${JAIL}" -U noroot xdg-settings get default-web-browser 2> /dev/null`

if [ "${DEFAULT_WEB_BROWSER}" = "x11appjail-OpenURL.desktop" ]; then
    exit 0
fi

appjail cmd jexec "${JAIL}" -U noroot \
    xdg-settings set default-web-browser x11appjail-OpenURL.desktop
