name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    steps:
      - uses: actions/checkout@v6
      - name: Build
        id: assets
        uses: vmactions/freebsd-vm@v1
        with:
          # Minimal production release for maximum compatibility.
          release: '14.4'
          usesh: true
          sync: rsync
          copyback: true
          prepare: |
            set -e -x
            set -o pipefail
            sed -i "" -e 's|quarterly|latest|g' /etc/pkg/FreeBSD.conf
            export IGNORE_OSVERSION=yes
            pkg update -f
            pkg install -y git-tiny aarch64-freebsd-sysroot
            git clone https://github.com/DtxdF/appscript.git
            (cd appscript; SUEXEC=command ./make.sh)
          run: |
            set -e -x
            set -o pipefail
            appscript -v
            make -j$(nproc) build-all
            make -j$(nproc) build-all ARCH=aarch64
            wait
      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          working_directory: assets/appscripts
          files: '*.appscript'
          generate_release_notes: true
          make_latest: true
